### ISSUE TITLE
[Pitch] Hashable QuadrupoleSettings

### ISSUE THREAD

**Issue by jspaezp** [MannLabs/timsrust#31]
Hey there!

I was wondering what you think about implementing Hash for the quad settings struct.
This would allow to easily do operations like "grouping all frames that share quad settings".

```
#[derive(Clone, Debug, Default, PartialEq)]
pub struct QuadrupoleSettings {
    pub index: usize,
    pub scan_starts: Vec<usize>,
    pub scan_ends: Vec<usize>,
    pub isolation_mz: Vec<f64>,
    pub isolation_width: Vec<f64>,
    pub collision_energy: Vec<f64>,
}

```

Rn the limiting factor is that f64 does not implement Hash ... and I can think of 2 workarounds ... 
    1. to use a fixed precision representation for the mzs and coll energy, I think this would make both on the programming and the instrument side of things.
    2. To just ignore those elements and hash based on the rest! this feels a bit more flaky but should work in most cases ... I cannot think of any instance where two quad settings would have the same index, same scan starts/ends but different collision energy ...

LMK what you think (happy to submit the PR)!

**Comment by sander-willems-bruker** [comment]
Done on develeop branch: https://github.com/MannLabs/timsrust/pull/33/commits/ae818253c505ba9084bb796b6222a2c1e2154dfd
