### ISSUE TITLE
[Question] Can the unit of RT be assumed?

### ISSUE THREAD

**Issue by jspaezp** [MannLabs/timsrust#34]
Here:
https://github.com/MannLabs/timsrust/blob/main/src/ms_data/frames.rs

There is no mention of what unit the retention time is meant to have. is it correct to assume that it will only be seconds?

Could the field be renamed to denote that?

**Comment by sander-willems-bruker** [comment]
Yes, it is in seconds indeed. I will try to make that explicit!

**Comment by sander-willems-bruker** [comment]
Turns out to be not invasive at all, although it might break backwards compatability as the public API changed, meaning we need a major version update: https://github.com/MannLabs/timsrust/pull/33/commits/1de3aeb203d2c3587afa705505cb6e2686a0c1d4
